name: Autoversion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - 'release/v*.*'

concurrency:
  group: bump-version-${{ github.ref }}
  cancel-in-progress: false

jobs:
  bump:
    if: ${{ !github.event.repository.fork }}
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@af83be0ddf1ec3035230c030f3ab6d10a7040515
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: |-
            ${{ github.token }}
            ${{ secrets.OPENAI_TOKEN }}
      - uses: plengauer/autoversion@bf2cffd5ba7126675b2e0da387a73c634d79892f # main
        with:
          github_token: ${{ github.token }}
          copilot_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          openai_token: ${{ secrets.OPENAI_TOKEN }}
          increments: ${{ github.ref_name == 'main' && 'major;minor' || 'patch' }}
