name: Autorerun

on:
  workflow_run:
    workflows: ['Release']
    types: completed
  schedule:
    - cron: '0 0 * * *'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@5d8cb00c1ec6a0a9772f30e7c3045d87b9f6609e # v5.58.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.ACTIONS_GITHUB_TOKEN }}"]'
      - uses: plengauer/autorerun@01cbbd02fa9641d3e243b12190be63c7aa3a13c5 # v0.38.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    permissions:
      actions: read
