name: 'Deploy OpenTelemetry'

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: otel-deploy-job-${{ github.ref_name }}
    permissions:
      contents: write
      pull-requests: write
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@a00ae915cd63b3c372c912ff7019e08a0934b441 # v5.61.1
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.ACTIONS_GITHUB_TOKEN }}","${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}","${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}"]'
      - uses: plengauer/opentelemetry-github/actions/instrument/deploy@a00ae915cd63b3c372c912ff7019e08a0934b441 # v5.61.1
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
        with:
          github_token: '${{ secrets.ACTIONS_GITHUB_TOKEN }}'
