name: OpenTelemetry
on:
  pull_request:
    types: [opened, reopened, closed]
  pull_request_review:
    types: [submitted]
  create:
  delete:
  push:
jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/repository@4b71071b2b044a176398118df98bb6b897a8458e # v5.61.4
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
    container: ghcr.io/plengauer/opentelemetry-github-workflow-instrumentation-runner:v5.61.4
