name: OpenTelemetry

on:
  workflow_run:
    workflows: [.github/workflows/copilot-setup-steps.yml, Autorerun, Autotriage, Claude, CodeQL, Copilot, Copilot cloud agent, Copilot code review, OpenAI Codex, Recompile Agentic Workflows, Release, Renovate, Report Failed Workflows]
    types:
      - completed

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/workflow@8a42906ace6a618a3b91545ef9b655b8c6d2ac23 # v5.54.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
    permissions:
      actions: read
    container: ghcr.io/plengauer/opentelemetry-github-workflow-instrumentation-runner:v5.55.0
